slice_name: Bridge Inflow (Count)
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 19__table
  viz_type: echarts_timeseries_bar
  slice_id: 43
  x_axis: created_at
  time_grain_sqla: P1W
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: false
    label: count()
    optionName: metric_58eo4ro6nb_cpt9g99ifd
    sqlExpression: count()
  groupby:
  - chain
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: created_at
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  stack: Stack
  only_total: true
  zoomable: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 6
cache_timeout: null
uuid: 3caef870-cfc6-404d-8edd-2a2696c2ba41
version: 1.0.0
dataset_uuid: 56644987-c213-4ded-be2e-8f5fa7b41c93
