slice_name: Centralized Exchange Inflow (Volume)
description: null
certified_by: null
certification_details: null
viz_type: echarts_area
params:
  datasource: 13__table
  viz_type: echarts_area
  slice_id: 23
  x_axis: created_at
  time_grain_sqla: P1D
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: deposit_amount
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 224
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: Float64
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(deposit_amount)
    optionName: metric_qzfupjirf2_fj47a4mj0q6
    sqlExpression: null
  groupby:
  - dst_label
  adhoc_filters:
  - expressionType: SIMPLE
    subject: created_at
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_6m0ptxir0zk_bu5zfbe99l
  - expressionType: SQL
    sqlExpression: src_label = ''
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_mf3wf01ofw_0r1438ae4uc
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  seriesType: line
  opacity: 0.3
  only_total: true
  markerSize: 6
  zoomable: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  logAxis: false
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":13,"type":"table"},"force":false,"queries":[{"filters":[{"col":"created_at","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":"(src_label = '''')"},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"created_at","label":"created_at","expressionType":"SQL"},"dst_label"],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"deposit_amount","description":null,"expression":null,"filterable":true,"groupby":true,"id":224,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"Float64","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(deposit_amount)","optionName":"metric_qzfupjirf2_fj47a4mj0q6","sqlExpression":null}],"orderby":[[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"deposit_amount","description":null,"expression":null,"filterable":true,"groupby":true,"id":224,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"Float64","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(deposit_amount)","optionName":"metric_qzfupjirf2_fj47a4mj0q6","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10000,"series_columns":["dst_label"],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["created_at"],"columns":["dst_label"],"aggregates":{"SUM(deposit_amount)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"SUM(deposit_amount)":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_6m0ptxir0zk_bu5zfbe99l","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"created_at"},{"clause":"WHERE","comparator":null,"datasourceWarning":false,"expressionType":"SQL","filterOptionName":"filter_mf3wf01ofw_0r1438ae4uc","isExtra":false,"isNew":false,"operator":null,"sqlExpression":"src_label
  = ''''","subject":null}],"annotation_layers":[],"color_scheme":"supersetColors","comparison_type":"values","dashboards":[1],"datasource":"13__table","extra_form_data":{},"forecastInterval":0.8,"forecastPeriods":10,"groupby":["dst_label"],"legendOrientation":"top","legendType":"scroll","logAxis":false,"markerSize":6,"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"deposit_amount","description":null,"expression":null,"filterable":true,"groupby":true,"id":224,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"Float64","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(deposit_amount)","optionName":"metric_qzfupjirf2_fj47a4mj0q6","sqlExpression":null}],"only_total":true,"opacity":0.3,"order_desc":true,"rich_tooltip":true,"row_limit":10000,"seriesType":"line","show_empty_columns":true,"show_legend":true,"slice_id":40,"sort_series_type":"sum","time_grain_sqla":"P1D","tooltipTimeFormat":"smart_date","truncate_metric":true,"viz_type":"echarts_area","x_axis":"created_at","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"x_axis_time_format":"smart_date","x_axis_title_margin":15,"y_axis_bounds":[null,null],"y_axis_format":"SMART_NUMBER","y_axis_title_margin":15,"y_axis_title_position":"Left","zoomable":true,"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: a69e305e-17f8-4d1e-9a44-5705a4d7613b
version: 1.0.0
dataset_uuid: fdd9d9f9-b89a-495b-8125-b09922f110bc
