slice_name: CEX Withdrawing Addresses
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 17__table
  viz_type: echarts_timeseries_line
  slice_id: 26
  x_axis: created_at
  time_grain_sqla: P1D
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: false
    label: uniqExact(dst_address)
    optionName: metric_fdmomfi3ynv_oau0slbmwts
    sqlExpression: uniqExact(dst_address)
  groupby: []
  adhoc_filters:
  - expressionType: SIMPLE
    subject: created_at
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_c5pc8c18278_lhdm60xe1b
  - expressionType: SQL
    sqlExpression: dst_label = ''
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_1nkweiyjb3q_ss03vcc4our
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  seriesType: line
  only_total: true
  opacity: 0.2
  markerSize: 6
  zoomable: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  granularity_sqla: created_at
  extra_form_data: {}
  dashboards:
  - 2
query_context: null
cache_timeout: null
uuid: d955fcdc-5c11-49aa-aaac-8fcf753a0a3c
version: 1.0.0
dataset_uuid: 1edc0a6f-bdf4-4854-8265-7fbfe086df0b
