slice_name: DeDust Total Number of Swaps
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 28__table
  viz_type: big_number_total
  metric:
    expressionType: SQL
    sqlExpression: COUNT(*)
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: false
    label: COUNT(*)
    optionName: metric_tkfevcv5db_xpkf63m30ck
  adhoc_filters:
  - expressionType: SIMPLE
    subject: created_at
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_wr2se4lik0k_yzvdn0myqwb
  - expressionType: SQL
    sqlExpression: operation_type = 'swap'
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_7m2h2j2bv7j_vn2zdsjqepn
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  extra_form_data: {}
  dashboards:
  - 7
query_context: '{"datasource":{"id":28,"type":"table"},"force":false,"queries":[{"filters":[{"col":"created_at","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":"(operation_type = ''swap'')"},"applied_time_extras":{},"columns":[],"metrics":[{"expressionType":"SQL","sqlExpression":"COUNT(*)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT(*)","optionName":"metric_tkfevcv5db_xpkf63m30ck"}],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"28__table","viz_type":"big_number_total","metric":{"expressionType":"SQL","sqlExpression":"COUNT(*)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT(*)","optionName":"metric_tkfevcv5db_xpkf63m30ck"},"adhoc_filters":[{"expressionType":"SIMPLE","subject":"created_at","operator":"TEMPORAL_RANGE","comparator":"No
  filter","clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_wr2se4lik0k_yzvdn0myqwb"},{"expressionType":"SQL","sqlExpression":"operation_type
  = ''swap''","clause":"WHERE","subject":null,"operator":null,"comparator":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_7m2h2j2bv7j_vn2zdsjqepn"}],"header_font_size":0.4,"subheader_font_size":0.15,"y_axis_format":"SMART_NUMBER","time_format":"smart_date","extra_form_data":{},"dashboards":[7],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 606d9de1-ba57-4359-8ce2-3482fa9165c4
version: 1.0.0
dataset_uuid: 0b9819a4-073f-448a-a875-708989fbcd91
