slice_name: Notcoin Vouchers Price and Volume (TON)
description: null
certified_by: null
certification_details: null
viz_type: mixed_timeseries
params:
  datasource: 37__table
  viz_type: mixed_timeseries
  x_axis: created_at
  time_grain_sqla: P1D
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: price_per_notcoin
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 291
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: NUMERIC
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: AVG
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Average Price
    optionName: metric_d3lu9h5k0ta_lwupiyqxp2
  groupby: []
  adhoc_filters:
  - clause: WHERE
    subject: created_at
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  comparison_type: values
  metrics_b:
  - expressionType: SQL
    sqlExpression: SUM(price_per_notcoin * voucher_value)
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Volume
    optionName: metric_ox43qyxk1v_5qh1bhipkq
  groupby_b: []
  adhoc_filters_b:
  - clause: WHERE
    subject: created_at
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  order_desc_b: true
  row_limit_b: 10000
  truncate_metric_b: true
  comparison_type_b: values
  annotation_layers: []
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  color_scheme: supersetColors
  seriesType: smooth
  stack: false
  area: true
  opacity: 0.3
  markerSize: 6
  yAxisIndex: 1
  seriesTypeB: bar
  areaB: true
  show_valueB: false
  opacityB: 0
  markerEnabledB: false
  markerSizeB: 8
  yAxisIndexB: 0
  zoomable: false
  minorTicks: false
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  truncateXAxis: false
  truncateYAxis: true
  y_axis_bounds:
  - null
  - 1000000
  y_axis_format: SMART_NUMBER
  logAxis: false
  y_axis_bounds_secondary:
  - 0
  - 0.008
  y_axis_format_secondary: SMART_NUMBER
  logAxisSecondary: false
  extra_form_data: {}
  dashboards:
  - 14
query_context: '{"datasource":{"id":37,"type":"table"},"force":false,"queries":[{"filters":[{"col":"created_at","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"created_at","label":"created_at","expressionType":"SQL"}],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"price_per_notcoin","description":null,"expression":null,"filterable":true,"groupby":true,"id":291,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"NUMERIC","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"AVG","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Average
  Price","optionName":"metric_d3lu9h5k0ta_lwupiyqxp2"}],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["created_at"],"columns":[],"aggregates":{"Average
  Price":{"operator":"mean"}},"drop_missing_columns":true}},{"operation":"flatten"}],"orderby":[[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"price_per_notcoin","description":null,"expression":null,"filterable":true,"groupby":true,"id":291,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"NUMERIC","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"AVG","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Average
  Price","optionName":"metric_d3lu9h5k0ta_lwupiyqxp2"},false]]},{"filters":[{"col":"created_at","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"created_at","label":"created_at","expressionType":"SQL"}],"metrics":[{"expressionType":"SQL","sqlExpression":"SUM(price_per_notcoin
  * voucher_value)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Volume","optionName":"metric_ox43qyxk1v_5qh1bhipkq"}],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["created_at"],"columns":[],"aggregates":{"Volume":{"operator":"mean"}},"drop_missing_columns":true}},{"operation":"flatten"}],"orderby":[[{"expressionType":"SQL","sqlExpression":"SUM(price_per_notcoin
  * voucher_value)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Volume","optionName":"metric_ox43qyxk1v_5qh1bhipkq"},false]]}],"form_data":{"datasource":"37__table","viz_type":"mixed_timeseries","x_axis":"created_at","time_grain_sqla":"P1D","metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"price_per_notcoin","description":null,"expression":null,"filterable":true,"groupby":true,"id":291,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"NUMERIC","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"AVG","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Average
  Price","optionName":"metric_d3lu9h5k0ta_lwupiyqxp2"}],"groupby":[],"adhoc_filters":[{"clause":"WHERE","subject":"created_at","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"order_desc":true,"row_limit":10000,"truncate_metric":true,"comparison_type":"values","annotation_layers":[],"x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","color_scheme":"supersetColors","seriesType":"smooth","stack":false,"area":true,"opacity":0.3,"markerSize":6,"yAxisIndex":1,"seriesTypeB":"bar","areaB":true,"show_valueB":false,"opacityB":0,"markerEnabledB":false,"markerSizeB":8,"yAxisIndexB":0,"zoomable":false,"minorTicks":false,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","rich_tooltip":true,"tooltipTimeFormat":"smart_date","truncateXAxis":false,"truncateYAxis":true,"y_axis_bounds":[null,1000000],"y_axis_format":"SMART_NUMBER","logAxis":false,"y_axis_bounds_secondary":[0,0.008],"y_axis_format_secondary":"SMART_NUMBER","logAxisSecondary":false,"extra_form_data":{},"dashboards":[14],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: ef7e12cf-19d3-4a27-90ce-791987a68c64
version: 1.0.0
dataset_uuid: 7a8e1eb0-bef2-47a7-9e1e-cd0d9026524a
