slice_name: Number of Active Wallets
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 18__table
  viz_type: echarts_timeseries_line
  slice_id: 17
  x_axis: updated_at
  time_grain_sqla: P1D
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: false
    label: uniqExact(address)
    optionName: metric_i42s5su8cmk_c3mxs2vqhp8
    sqlExpression: uniqExact(address)
  groupby: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_7rg0f724llu_wto23qzpm7g
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: updated_at
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SQL
    filterOptionName: filter_ar72zmqfpfc_mdr69jbpsmh
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: 'hasAny(types, [''wallet_v1r1'', ''wallet_v1r2'', ''wallet_v1r3'',
      ''wallet_v2r1'', ''wallet_v2r2'', ''wallet_v3r1'', ''wallet_v3r2'', ''wallet_v4r1'',
      ''wallet_v4r2'', ''wallet_lockup'', ''wallet_highload_v1r1'', ''wallet_highload_v1r2'',
      ''wallet_highload_v2r1'', ''wallet_highload_v2r2''])

      '
    subject: null
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  seriesType: line
  only_total: true
  opacity: 0.2
  markerSize: 6
  zoomable: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":18,"type":"table"},"force":false,"queries":[{"filters":[{"col":"updated_at","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":"(hasAny(types,
  [''wallet_v1r1'', ''wallet_v1r2'', ''wallet_v1r3'', ''wallet_v2r1'', ''wallet_v2r2'',
  ''wallet_v3r1'', ''wallet_v3r2'', ''wallet_v4r1'', ''wallet_v4r2'', ''wallet_lockup'',
  ''wallet_highload_v1r1'', ''wallet_highload_v1r2'', ''wallet_highload_v2r1'', ''wallet_highload_v2r2''])\n)"},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"updated_at","label":"updated_at","expressionType":"SQL"}],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"uniqExact(address)","optionName":"metric_i42s5su8cmk_c3mxs2vqhp8","sqlExpression":"uniqExact(address)"}],"orderby":[[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"uniqExact(address)","optionName":"metric_i42s5su8cmk_c3mxs2vqhp8","sqlExpression":"uniqExact(address)"},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["updated_at"],"columns":[],"aggregates":{"uniqExact(address)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_7rg0f724llu_wto23qzpm7g","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"updated_at"},{"clause":"WHERE","comparator":null,"datasourceWarning":false,"expressionType":"SQL","filterOptionName":"filter_ar72zmqfpfc_mdr69jbpsmh","isExtra":false,"isNew":false,"operator":null,"sqlExpression":"hasAny(types,
  [''wallet_v1r1'', ''wallet_v1r2'', ''wallet_v1r3'', ''wallet_v2r1'', ''wallet_v2r2'',
  ''wallet_v3r1'', ''wallet_v3r2'', ''wallet_v4r1'', ''wallet_v4r2'', ''wallet_lockup'',
  ''wallet_highload_v1r1'', ''wallet_highload_v1r2'', ''wallet_highload_v2r1'', ''wallet_highload_v2r2''])\n","subject":null}],"annotation_layers":[],"color_scheme":"supersetColors","comparison_type":"values","dashboards":[],"datasource":"18__table","extra_form_data":{},"forecastInterval":0.8,"forecastPeriods":10,"groupby":[],"legendOrientation":"top","legendType":"scroll","markerSize":6,"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"uniqExact(address)","optionName":"metric_i42s5su8cmk_c3mxs2vqhp8","sqlExpression":"uniqExact(address)"}],"only_total":true,"opacity":0.2,"order_desc":true,"rich_tooltip":true,"row_limit":10000,"seriesType":"line","show_empty_columns":true,"show_legend":true,"slice_id":22,"sort_series_type":"sum","time_grain_sqla":"P1D","tooltipTimeFormat":"smart_date","truncate_metric":true,"viz_type":"echarts_timeseries_line","x_axis":"updated_at","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"x_axis_time_format":"smart_date","x_axis_title_margin":15,"y_axis_bounds":[null,null],"y_axis_format":"SMART_NUMBER","y_axis_title_margin":15,"y_axis_title_position":"Left","zoomable":true,"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 1cd419c2-7355-46a4-ad27-e28bbf2f7425
version: 1.0.0
dataset_uuid: 79c170c9-44a8-40d7-8723-5c5b02aa4066
