slice_name: Number of Wallets by Balance
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 20__table
  viz_type: echarts_timeseries_line
  slice_id: 48
  x_axis: updated_at
  time_grain_sqla: P1D
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: false
    label: max(number_of_wallets)
    optionName: metric_m94bnv60y6h_h6q3r78p7b
    sqlExpression: max(number_of_wallets)
  groupby:
  - balance
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: updated_at
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  seriesType: smooth
  show_value: false
  only_total: true
  area: true
  opacity: 0.2
  markerSize: 6
  zoomable: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipSortByMetric: false
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards:
  - 2
query_context: '{"datasource":{"id":20,"type":"table"},"force":false,"queries":[{"filters":[{"col":"updated_at","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"updated_at","label":"updated_at","expressionType":"SQL"},"balance"],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"max(number_of_wallets)","optionName":"metric_m94bnv60y6h_h6q3r78p7b","sqlExpression":"max(number_of_wallets)"}],"orderby":[[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"max(number_of_wallets)","optionName":"metric_m94bnv60y6h_h6q3r78p7b","sqlExpression":"max(number_of_wallets)"},false]],"annotation_layers":[],"row_limit":10000,"series_columns":["balance"],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["updated_at"],"columns":["balance"],"aggregates":{"max(number_of_wallets)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"max(number_of_wallets)":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"20__table","viz_type":"echarts_timeseries_line","slice_id":48,"x_axis":"updated_at","time_grain_sqla":"P1D","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"max(number_of_wallets)","optionName":"metric_m94bnv60y6h_h6q3r78p7b","sqlExpression":"max(number_of_wallets)"}],"groupby":["balance"],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"updated_at"}],"order_desc":true,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","seriesType":"smooth","show_value":false,"only_total":true,"area":true,"opacity":0.2,"markerSize":6,"zoomable":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","rich_tooltip":true,"tooltipSortByMetric":false,"tooltipTimeFormat":"smart_date","y_axis_format":"SMART_NUMBER","truncateXAxis":true,"y_axis_bounds":[null,null],"extra_form_data":{},"dashboards":[2],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 6960a390-1b8a-48f5-afc3-f749d47d7a76
version: 1.0.0
dataset_uuid: 6b6a161c-281d-4594-8872-a3b1eec35509
