slice_name: Number of Wallets by Balance
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  datasource: 14__table
  viz_type: pie
  slice_id: 22
  groupby:
  - expressionType: SQL
    label: My column
    sqlExpression: "roundDown(balance, [100, 1000, 10000, 100000, 1000000,\n     \
      \ 10000000])"
  metric: count
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_hboi8pnmch_x8tbkvvhlae
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: updated_at
  - clause: WHERE
    comparator: '100'
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_xnaq7wt4fya_wf3imkmawh8
    isExtra: false
    isNew: false
    operator: '>'
    operatorId: GREATER_THAN
    sqlExpression: null
    subject: balance
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SQL
    filterOptionName: filter_tke7on633va_ue0tjmek3nh
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: hasAny(interfaces, ['wallet_v1r1', 'wallet_v1r2', 'wallet_v1r3',
      'wallet_v2r1', 'wallet_v2r2', 'wallet_v3r1', 'wallet_v3r2', 'wallet_v4r1', 'wallet_v4r2',
      'wallet_lockup', 'wallet_highload_v1r1', 'wallet_highload_v1r2', 'wallet_highload_v2r1',
      'wallet_highload_v2r2'])
    subject: null
  row_limit: 100
  sort_by_metric: true
  color_scheme: supersetColors
  show_labels_threshold: 5
  show_legend: true
  legendType: scroll
  legendOrientation: top
  legendMargin: null
  label_type: key_value_percent
  number_format: SMART_NUMBER
  date_format: smart_date
  show_labels: true
  labels_outside: true
  show_total: true
  outerRadius: 81
  donut: true
  innerRadius: 30
  extra_form_data: {}
  dashboards:
  - 1
cache_timeout: null
uuid: 53266c00-0806-40c0-93e9-db700ea39283
version: 1.0.0
dataset_uuid: 14757eac-4938-4795-8039-02fa4c83fa47
