slice_name: Number of Notcoin Voucher Traders
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 37__table
  viz_type: echarts_timeseries_bar
  x_axis: created_at
  time_grain_sqla: P1D
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - expressionType: SQL
    sqlExpression: COUNT(DISTINCT seller_address)
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Sellers
    optionName: metric_lakj6ni6fzl_53qvcogri2u
  - expressionType: SQL
    sqlExpression: COUNT(DISTINCT buyer_address)
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Buyers
    optionName: metric_xvnlwlr6u1_k1v3zi7vsfb
  groupby: []
  adhoc_filters:
  - clause: WHERE
    subject: created_at
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  stack: Stack
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 14
query_context: '{"datasource":{"id":37,"type":"table"},"force":false,"queries":[{"filters":[{"col":"created_at","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"created_at","label":"created_at","expressionType":"SQL"}],"metrics":[{"expressionType":"SQL","sqlExpression":"COUNT(DISTINCT
  seller_address)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Sellers","optionName":"metric_lakj6ni6fzl_53qvcogri2u"},{"expressionType":"SQL","sqlExpression":"COUNT(DISTINCT
  buyer_address)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Buyers","optionName":"metric_xvnlwlr6u1_k1v3zi7vsfb"}],"orderby":[[{"expressionType":"SQL","sqlExpression":"COUNT(DISTINCT
  seller_address)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Sellers","optionName":"metric_lakj6ni6fzl_53qvcogri2u"},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["created_at"],"columns":[],"aggregates":{"Sellers":{"operator":"mean"},"Buyers":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"37__table","viz_type":"echarts_timeseries_bar","x_axis":"created_at","time_grain_sqla":"P1D","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"expressionType":"SQL","sqlExpression":"COUNT(DISTINCT
  seller_address)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Sellers","optionName":"metric_lakj6ni6fzl_53qvcogri2u"},{"expressionType":"SQL","sqlExpression":"COUNT(DISTINCT
  buyer_address)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Buyers","optionName":"metric_xvnlwlr6u1_k1v3zi7vsfb"}],"groupby":[],"adhoc_filters":[{"clause":"WHERE","subject":"created_at","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"order_desc":true,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","stack":"Stack","only_total":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","y_axis_format":"SMART_NUMBER","truncateXAxis":true,"y_axis_bounds":[null,null],"rich_tooltip":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[14],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 22f96ee1-0e86-4cc0-95b2-f54970650bd8
version: 1.0.0
dataset_uuid: 7a8e1eb0-bef2-47a7-9e1e-cd0d9026524a
