slice_name: Number of Active NFT Items
description: null
certified_by: null
certification_details: null
viz_type: echarts_area
params:
  datasource: 3__table
  viz_type: echarts_area
  slice_id: 31
  x_axis: updated_at
  time_grain_sqla: P1D
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: false
    label: uniqExact(address)
    optionName: metric_xhk8hebid7_4fhbdx8yx7
    sqlExpression: uniqExact(address)
  groupby:
  - types
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_8dg7l3zvja5_k251rykxmh
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: updated_at
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SQL
    filterOptionName: filter_temlko9exk_27wsk5izjvp
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: hasAny(types, ['nft_item'])
    subject: null
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  seriesType: line
  opacity: 0.2
  only_total: true
  markerSize: 6
  zoomable: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards:
  - 1
cache_timeout: null
uuid: c4d32eb2-8d56-4a50-8734-edb638fe3b7b
version: 1.0.0
dataset_uuid: 79c170c9-44a8-40d7-8723-5c5b02aa4066
