slice_name: StonFi Operations Volume (pTON)
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 30__table
  viz_type: echarts_timeseries_bar
  slice_id: 77
  x_axis: created_at
  time_grain_sqla: P1W
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: false
    label: 'sum(case when asset_0_jetton_address = decode(''001150b518b2626ad51899f98887f8824b70065456455f7fe2813f012699a4061f'',
      ''hex'') then asset_0_amount / 1e9

      when asset_1_jetton_address = decode(''001150b518b2626ad51899f98887f8824b70065456455f7fe2813f012699a4061f'',
      ''hex'') then asset_1_amount / 1e9

      end)'
    optionName: metric_eeysdfodeqq_v6xenze2ta
    sqlExpression: 'sum(case when asset_0_jetton_address = decode(''001150b518b2626ad51899f98887f8824b70065456455f7fe2813f012699a4061f'',
      ''hex'') then asset_0_amount / 1e9

      when asset_1_jetton_address = decode(''001150b518b2626ad51899f98887f8824b70065456455f7fe2813f012699a4061f'',
      ''hex'') then asset_1_amount / 1e9

      end)'
  groupby:
  - operation_type
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: created_at
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  stack: Stack
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 13
query_context: '{"datasource":{"id":30,"type":"table"},"force":false,"queries":[{"filters":[{"col":"created_at","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1W","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1W","columnType":"BASE_AXIS","sqlExpression":"created_at","label":"created_at","expressionType":"SQL"},"operation_type"],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"sum(case
  when asset_0_jetton_address = decode(''001150b518b2626ad51899f98887f8824b70065456455f7fe2813f012699a4061f'',
  ''hex'') then asset_0_amount / 1e9\nwhen asset_1_jetton_address = decode(''001150b518b2626ad51899f98887f8824b70065456455f7fe2813f012699a4061f'',
  ''hex'') then asset_1_amount / 1e9\nend)","optionName":"metric_eeysdfodeqq_v6xenze2ta","sqlExpression":"sum(case
  when asset_0_jetton_address = decode(''001150b518b2626ad51899f98887f8824b70065456455f7fe2813f012699a4061f'',
  ''hex'') then asset_0_amount / 1e9\nwhen asset_1_jetton_address = decode(''001150b518b2626ad51899f98887f8824b70065456455f7fe2813f012699a4061f'',
  ''hex'') then asset_1_amount / 1e9\nend)"}],"orderby":[[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"sum(case
  when asset_0_jetton_address = decode(''001150b518b2626ad51899f98887f8824b70065456455f7fe2813f012699a4061f'',
  ''hex'') then asset_0_amount / 1e9\nwhen asset_1_jetton_address = decode(''001150b518b2626ad51899f98887f8824b70065456455f7fe2813f012699a4061f'',
  ''hex'') then asset_1_amount / 1e9\nend)","optionName":"metric_eeysdfodeqq_v6xenze2ta","sqlExpression":"sum(case
  when asset_0_jetton_address = decode(''001150b518b2626ad51899f98887f8824b70065456455f7fe2813f012699a4061f'',
  ''hex'') then asset_0_amount / 1e9\nwhen asset_1_jetton_address = decode(''001150b518b2626ad51899f98887f8824b70065456455f7fe2813f012699a4061f'',
  ''hex'') then asset_1_amount / 1e9\nend)"},false]],"annotation_layers":[],"row_limit":10000,"series_columns":["operation_type"],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["created_at"],"columns":["operation_type"],"aggregates":{"sum(case
  when asset_0_jetton_address = decode(''001150b518b2626ad51899f98887f8824b70065456455f7fe2813f012699a4061f'',
  ''hex'') then asset_0_amount / 1e9\nwhen asset_1_jetton_address = decode(''001150b518b2626ad51899f98887f8824b70065456455f7fe2813f012699a4061f'',
  ''hex'') then asset_1_amount / 1e9\nend)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"sum(case
  when asset_0_jetton_address = decode(''001150b518b2626ad51899f98887f8824b70065456455f7fe2813f012699a4061f'',
  ''hex'') then asset_0_amount / 1e9\nwhen asset_1_jetton_address = decode(''001150b518b2626ad51899f98887f8824b70065456455f7fe2813f012699a4061f'',
  ''hex'') then asset_1_amount / 1e9\nend)":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"30__table","viz_type":"echarts_timeseries_bar","slice_id":77,"x_axis":"created_at","time_grain_sqla":"P1W","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"sum(case
  when asset_0_jetton_address = decode(''001150b518b2626ad51899f98887f8824b70065456455f7fe2813f012699a4061f'',
  ''hex'') then asset_0_amount / 1e9\nwhen asset_1_jetton_address = decode(''001150b518b2626ad51899f98887f8824b70065456455f7fe2813f012699a4061f'',
  ''hex'') then asset_1_amount / 1e9\nend)","optionName":"metric_eeysdfodeqq_v6xenze2ta","sqlExpression":"sum(case
  when asset_0_jetton_address = decode(''001150b518b2626ad51899f98887f8824b70065456455f7fe2813f012699a4061f'',
  ''hex'') then asset_0_amount / 1e9\nwhen asset_1_jetton_address = decode(''001150b518b2626ad51899f98887f8824b70065456455f7fe2813f012699a4061f'',
  ''hex'') then asset_1_amount / 1e9\nend)"}],"groupby":["operation_type"],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"created_at"}],"order_desc":true,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","stack":"Stack","only_total":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","y_axis_format":"SMART_NUMBER","truncateXAxis":true,"y_axis_bounds":[null,null],"rich_tooltip":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[13],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 32f785c0-0092-479e-a45f-f9aa90ade41a
version: 1.0.0
dataset_uuid: 06be013b-d654-48c0-90a2-aa053767b5ed
