slice_name: Telegram Numbers On Sale
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 6__table
  viz_type: echarts_timeseries_bar
  slice_id: 3
  x_axis: max_bid
  time_grain_sqla: P1D
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - count
  groupby: []
  adhoc_filters:
  - expressionType: SIMPLE
    subject: updated_at
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_f8nsiiqjg7l_ezw22ehtp9
  - expressionType: SIMPLE
    subject: max_bid
    operator: '!='
    operatorId: NOT_EQUALS
    comparator: '0'
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_wbzp19g902r_mikhrgc5ngs
  - expressionType: SIMPLE
    subject: max_bid
    operator: <
    operatorId: LESS_THAN
    comparator: '1000'
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_1qjtk2lximn_r6lhq5b6zng
  - expressionType: SQL
    sqlExpression: fake = false
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_xs0qt315zj_emgrsp9jxzh
  order_desc: true
  row_limit: 1000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title: Price
  x_axis_title_margin: 30
  y_axis_title: Count
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  only_total: true
  zoomable: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 4
query_context: '{"datasource":{"id":6,"type":"table"},"force":false,"queries":[{"filters":[{"col":"updated_at","op":"TEMPORAL_RANGE","val":"No
  filter"},{"col":"max_bid","op":"!=","val":"0"},{"col":"max_bid","op":"<","val":"1000"}],"extras":{"time_grain_sqla":"P1D","having":"","where":"(fake
  = false)"},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"max_bid","label":"max_bid","expressionType":"SQL"}],"metrics":["count"],"orderby":[["count",false]],"annotation_layers":[],"row_limit":1000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["max_bid"],"columns":[],"aggregates":{"count":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"6__table","viz_type":"echarts_timeseries_bar","slice_id":3,"x_axis":"max_bid","time_grain_sqla":"P1D","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":["count"],"groupby":[],"adhoc_filters":[{"expressionType":"SIMPLE","subject":"updated_at","operator":"TEMPORAL_RANGE","comparator":"No
  filter","clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_f8nsiiqjg7l_ezw22ehtp9"},{"expressionType":"SIMPLE","subject":"max_bid","operator":"!=","operatorId":"NOT_EQUALS","comparator":"0","clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_wbzp19g902r_mikhrgc5ngs"},{"expressionType":"SIMPLE","subject":"max_bid","operator":"<","operatorId":"LESS_THAN","comparator":"1000","clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_1qjtk2lximn_r6lhq5b6zng"},{"expressionType":"SQL","sqlExpression":"fake
  = false","clause":"WHERE","subject":null,"operator":null,"comparator":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_xs0qt315zj_emgrsp9jxzh"}],"order_desc":true,"row_limit":1000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title":"Price","x_axis_title_margin":30,"y_axis_title":"Count","y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","only_total":true,"zoomable":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","y_axis_format":"SMART_NUMBER","truncateXAxis":true,"y_axis_bounds":[null,null],"rich_tooltip":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[4],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 31b6647b-68ca-4e78-826a-d230d7dae222
version: 1.0.0
dataset_uuid: f8673afc-4d5f-4845-bc27-34c39d12bbc9
