slice_name: Telegram Numbers Daily Average Sale Price
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 23__table
  viz_type: echarts_timeseries_bar
  slice_id: 11
  x_axis: created_at
  time_grain_sqla: P1D
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - expressionType: SQL
    sqlExpression: AVG(sale_price / 1e9)
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: false
    label: AVG(sale_price / 1e9)
    optionName: metric_ssj77oig21_msqzd2eza57
  groupby: []
  adhoc_filters:
  - expressionType: SQL
    sqlExpression: sale_type = 'secondary_sale'::telemint_sale_type
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_3q7kgxelc5p_b3qn0ptavtk
  - expressionType: SIMPLE
    subject: created_at
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_2x3m52ard2m_mpxfyja8r8s
  - expressionType: SQL
    sqlExpression: fake_item = false
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_k7q2l8kmux_zxi8739j11
  - expressionType: SQL
    sqlExpression: minter_address = decode('000E41DC1DC3C9067ED24248580E12B3359818D83DEE0304FABCF80845EAFAFDB2',
      'hex')
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_vg3ej6mtmo_hz80dm6suuc
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  rolling_type: null
  rolling_periods: 30
  min_periods: 30
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title: Price
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  stack: Stack
  only_total: true
  zoomable: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 4
query_context: '{"datasource":{"id":23,"type":"table"},"force":false,"queries":[{"filters":[{"col":"created_at","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":"(sale_type = ''secondary_sale''::telemint_sale_type)
  AND (fake_item = false) AND (minter_address = decode(''000E41DC1DC3C9067ED24248580E12B3359818D83DEE0304FABCF80845EAFAFDB2'',
  ''hex''))"},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"created_at","label":"created_at","expressionType":"SQL"}],"metrics":[{"expressionType":"SQL","sqlExpression":"AVG(sale_price
  / 1e9)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"AVG(sale_price
  / 1e9)","optionName":"metric_ssj77oig21_msqzd2eza57"}],"orderby":[[{"expressionType":"SQL","sqlExpression":"AVG(sale_price
  / 1e9)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"AVG(sale_price
  / 1e9)","optionName":"metric_ssj77oig21_msqzd2eza57"},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["created_at"],"columns":[],"aggregates":{"AVG(sale_price
  / 1e9)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"23__table","viz_type":"echarts_timeseries_bar","slice_id":11,"x_axis":"created_at","time_grain_sqla":"P1D","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"expressionType":"SQL","sqlExpression":"AVG(sale_price
  / 1e9)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"AVG(sale_price
  / 1e9)","optionName":"metric_ssj77oig21_msqzd2eza57"}],"groupby":[],"adhoc_filters":[{"expressionType":"SQL","sqlExpression":"sale_type
  = ''secondary_sale''::telemint_sale_type","clause":"WHERE","subject":null,"operator":null,"comparator":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_3q7kgxelc5p_b3qn0ptavtk"},{"expressionType":"SIMPLE","subject":"created_at","operator":"TEMPORAL_RANGE","comparator":"No
  filter","clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_2x3m52ard2m_mpxfyja8r8s"},{"expressionType":"SQL","sqlExpression":"fake_item
  = false","clause":"WHERE","subject":null,"operator":null,"comparator":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_k7q2l8kmux_zxi8739j11"},{"expressionType":"SQL","sqlExpression":"minter_address
  = decode(''000E41DC1DC3C9067ED24248580E12B3359818D83DEE0304FABCF80845EAFAFDB2'',
  ''hex'')","clause":"WHERE","subject":null,"operator":null,"comparator":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_vg3ej6mtmo_hz80dm6suuc"}],"order_desc":true,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"rolling_type":null,"rolling_periods":30,"min_periods":30,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title_margin":15,"y_axis_title":"Price","y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","stack":"Stack","only_total":true,"zoomable":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","y_axis_format":"SMART_NUMBER","truncateXAxis":true,"y_axis_bounds":[null,null],"rich_tooltip":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[4],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 5a601e22-478c-4406-a7c7-6c4b50c0aae1
version: 1.0.0
dataset_uuid: 490b5032-9232-4ff0-8ca9-3c98c4b01557
