slice_name: TOP Telegram NFT Traders
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 25__table
  viz_type: table
  slice_id: 61
  query_mode: raw
  groupby: []
  time_grain_sqla: P1D
  temporal_columns_lookup: {}
  metrics: []
  all_columns:
  - expressionType: SQL
    label: trader_address
    sqlExpression: '''0:'' || encode(substring(trader_address, 2, 32), ''hex'')'
  - buy_volume
  - buy_count
  - sell_volume
  - sell_count
  percent_metrics: []
  adhoc_filters: []
  order_by_cols:
  - '["sell_volume", false]'
  row_limit: 1000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  page_length: 50
  include_search: true
  show_cell_bars: true
  color_pn: true
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 4
query_context: '{"datasource":{"id":25,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"expressionType":"SQL","label":"trader_address","sqlExpression":"''0:''
  || encode(substring(trader_address, 2, 32), ''hex'')"},"buy_volume","buy_count","sell_volume","sell_count"],"orderby":[["sell_volume",false]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[]}],"form_data":{"datasource":"25__table","viz_type":"table","slice_id":61,"query_mode":"raw","groupby":[],"time_grain_sqla":"P1D","temporal_columns_lookup":{},"metrics":[],"all_columns":[{"expressionType":"SQL","label":"trader_address","sqlExpression":"''0:''
  || encode(substring(trader_address, 2, 32), ''hex'')"},"buy_volume","buy_count","sell_volume","sell_count"],"percent_metrics":[],"adhoc_filters":[],"order_by_cols":["[\"sell_volume\",
  false]"],"row_limit":1000,"server_page_length":10,"order_desc":true,"table_timestamp_format":"smart_date","page_length":50,"include_search":true,"show_cell_bars":true,"color_pn":true,"conditional_formatting":[],"extra_form_data":{},"dashboards":[4],"force":false,"result_format":"json","result_type":"full","include_time":false},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 98d4ba94-bf0d-41f2-885a-6019f5b1ea6a
version: 1.0.0
dataset_uuid: 630ea06f-1286-4ce8-8bb3-3bfbe82957b8
