slice_name: TOP StonFi Traders
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 31__table
  viz_type: table
  query_mode: raw
  groupby: []
  time_grain_sqla: P1D
  temporal_columns_lookup: {}
  metrics: []
  all_columns:
  - label: trader_address
    sqlExpression: '''0:'' || encode(substring(trader_address, 2, 32), ''hex'')'
    expressionType: SQL
  - buy_volume
  - buy_count
  - sell_volume
  - sell_count
  percent_metrics: []
  adhoc_filters:
  - expressionType: SQL
    sqlExpression: sell_volume is not null
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_gi35jrszghj_ixuw8hed339
  order_by_cols:
  - '["sell_volume", false]'
  row_limit: 1000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  page_length: 50
  include_search: true
  show_cell_bars: true
  color_pn: true
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 13
query_context: '{"datasource":{"id":31,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"time_grain_sqla":"P1D","having":"","where":"(sell_volume
  is not null)"},"applied_time_extras":{},"columns":[{"label":"trader_address","sqlExpression":"''0:''
  || encode(substring(trader_address, 2, 32), ''hex'')","expressionType":"SQL"},"buy_volume","buy_count","sell_volume","sell_count"],"orderby":[["sell_volume",false]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[]}],"form_data":{"datasource":"31__table","viz_type":"table","query_mode":"raw","groupby":[],"time_grain_sqla":"P1D","temporal_columns_lookup":{},"metrics":[],"all_columns":[{"label":"trader_address","sqlExpression":"''0:''
  || encode(substring(trader_address, 2, 32), ''hex'')","expressionType":"SQL"},"buy_volume","buy_count","sell_volume","sell_count"],"percent_metrics":[],"adhoc_filters":[{"expressionType":"SQL","sqlExpression":"sell_volume
  is not null","clause":"WHERE","subject":null,"operator":null,"comparator":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_gi35jrszghj_ixuw8hed339"}],"order_by_cols":["[\"sell_volume\",
  false]"],"row_limit":1000,"server_page_length":10,"order_desc":true,"table_timestamp_format":"smart_date","page_length":50,"include_search":true,"show_cell_bars":true,"color_pn":true,"conditional_formatting":[],"extra_form_data":{},"dashboards":[13],"force":false,"result_format":"json","result_type":"full","include_time":false},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 45e45c6f-4cb3-4a78-986b-680b0273b0ea
version: 1.0.0
dataset_uuid: 42bbb4d7-7634-4f05-a5d2-164f18d7c72b
