slice_name: Total Getgems Sales Volume
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 40__table
  viz_type: big_number_total
  slice_id: 52
  metric:
    aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: full_price
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 342
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: Float64
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(full_price)
    optionName: metric_hijn57837bh_dkdndcr8sr4
    sqlExpression: null
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: updated_at
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  granularity_sqla: updated_at
  extra_form_data: {}
  dashboards:
  - 3
cache_timeout: null
uuid: f724e9a8-73e9-4c79-b64e-3820918b9fe3
version: 1.0.0
dataset_uuid: c63eba40-4891-4891-b6b9-58da58538e56
