slice_name: Total Number of Notcoin Voucher Conversion Users
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 43__table
  viz_type: big_number_total
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: owner_address
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 322
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: BYTEA
      type_generic: null
      verbose_name: null
      warning_markdown: null
    aggregate: COUNT_DISTINCT
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: COUNT_DISTINCT(owner_address)
    optionName: metric_wbmkcy4upw_mh69yvksyg8
  adhoc_filters:
  - clause: WHERE
    subject: created_at
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  extra_form_data: {}
  dashboards:
  - 14
query_context: '{"datasource":{"id":43,"type":"table"},"force":false,"queries":[{"filters":[{"col":"created_at","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"owner_address","description":null,"expression":null,"filterable":true,"groupby":true,"id":322,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BYTEA","type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"COUNT_DISTINCT","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT_DISTINCT(owner_address)","optionName":"metric_wbmkcy4upw_mh69yvksyg8"}],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"43__table","viz_type":"big_number_total","metric":{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"owner_address","description":null,"expression":null,"filterable":true,"groupby":true,"id":322,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BYTEA","type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"COUNT_DISTINCT","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT_DISTINCT(owner_address)","optionName":"metric_wbmkcy4upw_mh69yvksyg8"},"adhoc_filters":[{"clause":"WHERE","subject":"created_at","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"header_font_size":0.4,"subheader_font_size":0.15,"y_axis_format":"SMART_NUMBER","time_format":"smart_date","extra_form_data":{},"dashboards":[14],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: a0929194-7fe4-4e06-aec6-8a3811a65969
version: 1.0.0
dataset_uuid: 60381d28-899b-4ee7-ad9c-706583a5568b
