slice_name: Total Number of Getgems Traders
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 40__table
  viz_type: big_number_total
  slice_id: 49
  metric:
    aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: false
    label: uniqExact(buyer_address)
    optionName: metric_zqhlpeyfi4l_cee9tksm2qt
    sqlExpression: uniqExact(buyer_address)
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: updated_at
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  granularity_sqla: updated_at
  extra_form_data: {}
  dashboards:
  - 3
cache_timeout: null
uuid: 375b8e95-a2fd-4f38-9eb9-19eb91cd70d3
version: 1.0.0
dataset_uuid: c63eba40-4891-4891-b6b9-58da58538e56
