slice_name: Total Number of Notcoin Vouchers Conversion Users
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 39__table
  viz_type: big_number_total
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: owner_address
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 298
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: BYTEA
      type_generic: null
      verbose_name: null
      warning_markdown: null
    aggregate: COUNT_DISTINCT
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: COUNT_DISTINCT(owner_address)
    optionName: metric_g4icpnynyr_ccbsjy47mlt
  adhoc_filters:
  - clause: WHERE
    subject: created_at
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  extra_form_data: {}
  dashboards:
  - 14
query_context: '{"datasource":{"id":39,"type":"table"},"force":false,"queries":[{"filters":[{"col":"created_at","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"owner_address","description":null,"expression":null,"filterable":true,"groupby":true,"id":298,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BYTEA","type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"COUNT_DISTINCT","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT_DISTINCT(owner_address)","optionName":"metric_g4icpnynyr_ccbsjy47mlt"}],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"39__table","viz_type":"big_number_total","metric":{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"owner_address","description":null,"expression":null,"filterable":true,"groupby":true,"id":298,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BYTEA","type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"COUNT_DISTINCT","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT_DISTINCT(owner_address)","optionName":"metric_g4icpnynyr_ccbsjy47mlt"},"adhoc_filters":[{"clause":"WHERE","subject":"created_at","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"header_font_size":0.4,"subheader_font_size":0.15,"y_axis_format":"SMART_NUMBER","time_format":"smart_date","extra_form_data":{},"dashboards":[14],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 9dc18620-e1f6-4d4f-ae19-46a17ae4fe98
version: 1.0.0
dataset_uuid: 6113a321-193b-4dcd-9c3e-a20f7d698abe
