slice_name: Total Number of wNOT/TON StonFi Pool Traders
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 41__table
  viz_type: big_number_total
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: trader_address
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 307
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: BYTEA
      type_generic: null
      verbose_name: null
      warning_markdown: null
    aggregate: COUNT_DISTINCT
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: COUNT_DISTINCT(trader_address)
    optionName: metric_u78a56c5am_2v48ehq3nxc
  adhoc_filters:
  - expressionType: SIMPLE
    subject: created_at
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_j288u89fhg_wu0kodmvqw
  - expressionType: SQL
    sqlExpression: pool_address = decode('007194e867aed719e1d45246c0b8facb07bdcba1cef2d5199ffac24531e3ad73a9',
      'hex')
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_94rf8bjyl2o_ehlb788aqfl
  - expressionType: SQL
    sqlExpression: operation_type = 'swap'
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_didbl3w6sas_m5uj7bng6q
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  extra_form_data: {}
  dashboards:
  - 14
query_context: '{"datasource":{"id":41,"type":"table"},"force":false,"queries":[{"filters":[{"col":"created_at","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":"(pool_address = decode(''007194e867aed719e1d45246c0b8facb07bdcba1cef2d5199ffac24531e3ad73a9'',
  ''hex'')) AND (operation_type = ''swap'')"},"applied_time_extras":{},"columns":[],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"trader_address","description":null,"expression":null,"filterable":true,"groupby":true,"id":307,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BYTEA","type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"COUNT_DISTINCT","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT_DISTINCT(trader_address)","optionName":"metric_u78a56c5am_2v48ehq3nxc"}],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"41__table","viz_type":"big_number_total","metric":{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"trader_address","description":null,"expression":null,"filterable":true,"groupby":true,"id":307,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BYTEA","type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"COUNT_DISTINCT","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT_DISTINCT(trader_address)","optionName":"metric_u78a56c5am_2v48ehq3nxc"},"adhoc_filters":[{"expressionType":"SIMPLE","subject":"created_at","operator":"TEMPORAL_RANGE","comparator":"No
  filter","clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_j288u89fhg_wu0kodmvqw"},{"expressionType":"SQL","sqlExpression":"pool_address
  = decode(''007194e867aed719e1d45246c0b8facb07bdcba1cef2d5199ffac24531e3ad73a9'',
  ''hex'')","clause":"WHERE","subject":null,"operator":null,"comparator":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_94rf8bjyl2o_ehlb788aqfl"},{"expressionType":"SQL","sqlExpression":"operation_type
  = ''swap''","clause":"WHERE","subject":null,"operator":null,"comparator":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_didbl3w6sas_m5uj7bng6q"}],"header_font_size":0.4,"subheader_font_size":0.15,"y_axis_format":"SMART_NUMBER","time_format":"smart_date","extra_form_data":{},"dashboards":[14],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: b38e1985-9c75-45a4-859d-009e51d989a5
version: 1.0.0
dataset_uuid: bdef4710-e815-41e1-9b98-40bd837a0bb4
