slice_name: wNOT -> NOT Conversions
description: null
certified_by: null
certification_details: null
viz_type: mixed_timeseries
params:
  datasource: 44__table
  viz_type: mixed_timeseries
  x_axis: created_at
  time_grain_sqla: P1D
  metrics:
  - expressionType: SQL
    sqlExpression: SUM(amount / 1e3 / 1e9)
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: NOT Amount
    optionName: metric_whrm3wwz2sp_9iw7ffqv4ir
  groupby: []
  adhoc_filters:
  - clause: WHERE
    subject: created_at
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  comparison_type: values
  metrics_b:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: tx_hash
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 325
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: BYTEA
      type_generic: null
      verbose_name: null
      warning_markdown: null
    aggregate: COUNT
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Tx Count
    optionName: metric_xr6omhn2b5_xzpu2drr43
  groupby_b: []
  adhoc_filters_b:
  - clause: WHERE
    subject: created_at
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  order_desc_b: true
  row_limit_b: 10000
  truncate_metric_b: true
  comparison_type_b: values
  annotation_layers: []
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  color_scheme: supersetColors
  seriesType: line
  area: true
  opacity: 0.2
  markerEnabled: true
  markerSize: 6
  seriesTypeB: bar
  opacityB: 0.2
  markerSizeB: 6
  yAxisIndexB: 1
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_bounds_secondary:
  - 0
  - 10000
  y_axis_format_secondary: SMART_NUMBER
  extra_form_data: {}
  dashboards:
  - 14
query_context: '{"datasource":{"id":44,"type":"table"},"force":false,"queries":[{"filters":[{"col":"created_at","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"created_at","label":"created_at","expressionType":"SQL"}],"metrics":[{"expressionType":"SQL","sqlExpression":"SUM(amount
  / 1e3 / 1e9)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"NOT
  Amount","optionName":"metric_whrm3wwz2sp_9iw7ffqv4ir"}],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["created_at"],"columns":[],"aggregates":{"NOT
  Amount":{"operator":"mean"}},"drop_missing_columns":true}},{"operation":"flatten"}],"orderby":[[{"expressionType":"SQL","sqlExpression":"SUM(amount
  / 1e3 / 1e9)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"NOT
  Amount","optionName":"metric_whrm3wwz2sp_9iw7ffqv4ir"},false]]},{"filters":[{"col":"created_at","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"created_at","label":"created_at","expressionType":"SQL"}],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"tx_hash","description":null,"expression":null,"filterable":true,"groupby":true,"id":325,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BYTEA","type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"COUNT","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Tx
  Count","optionName":"metric_xr6omhn2b5_xzpu2drr43"}],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["created_at"],"columns":[],"aggregates":{"Tx
  Count":{"operator":"mean"}},"drop_missing_columns":true}},{"operation":"flatten"}],"orderby":[[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"tx_hash","description":null,"expression":null,"filterable":true,"groupby":true,"id":325,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BYTEA","type_generic":null,"verbose_name":null,"warning_markdown":null},"aggregate":"COUNT","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Tx
  Count","optionName":"metric_xr6omhn2b5_xzpu2drr43"},false]]}],"form_data":{"datasource":"44__table","viz_type":"mixed_timeseries","x_axis":"created_at","time_grain_sqla":"P1D","metrics":[{"expressionType":"SQL","sqlExpression":"SUM(amount
  / 1e3 / 1e9)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"NOT
  Amount","optionName":"metric_whrm3wwz2sp_9iw7ffqv4ir"}],"groupby":[],"adhoc_filters":[{"clause":"WHERE","subject":"created_at","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"order_desc":true,"row_limit":10000,"truncate_metric":true,"comparison_type":"values","annotation_layers":[],"x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","color_scheme":"supersetColors","seriesType":"line","area":true,"opacity":0.2,"markerEnabled":true,"markerSize":6,"seriesTypeB":"bar","opacityB":0.2,"markerSizeB":6,"yAxisIndexB":1,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","rich_tooltip":true,"tooltipTimeFormat":"smart_date","truncateXAxis":true,"y_axis_bounds":[null,null],"y_axis_format":"SMART_NUMBER","y_axis_bounds_secondary":[0,10000],"y_axis_format_secondary":"SMART_NUMBER","extra_form_data":{},"dashboards":[14],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 64d33342-7805-4d19-9744-fc193758d01d
version: 1.0.0
dataset_uuid: 47291458-33d4-4a66-9f49-84be92813e28
